services:
  db:
    image: postgres:16
    container_name: mini-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: mini-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    container_name: mini-frontend
    restart: always
    depends_on:
      - app
    ports:
      - "5173:5173"