package org.example.systemuptimemonitor.servlets;

import org.example.systemuptimemonitor.model.InviteLink;
import org.example.systemuptimemonitor.model.User;
import org.example.systemuptimemonitor.services.InviteLinkService;
import org.example.systemuptimemonitor.util.ErrorResponse;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

@WebServlet("/generate_invitelink")
public class GenerateInviteLink extends HttpServlet {
    private static final Logger LOG = Logger.getLogger(GenerateInviteLink.class.getName());

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        User user = (User) req.getSession().getAttribute("user");
        String role = req.getParameter("role");
        if (role == null || !role.equals("operator") && !role.equals("viewer")) {
            ErrorResponse.sendJsonError(resp, HttpServletResponse.SC_BAD_REQUEST, "Role should be either operator or viewer");
            return;
        }

        String url = "" + System.currentTimeMillis();
        InviteLink inviteLink = new InviteLink(user.getId(), System.currentTimeMillis(), false, url, role);
        InviteLinkService inviteLinkService = new InviteLinkService();

        try {
            inviteLinkService.createInviteLink(inviteLink);
            LOG.info("Invite link generated by user " + user.getEmail() + " for role: " + role);
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Failed to generate invite link", e);
            ErrorResponse.sendJsonError(resp, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Server error");
            return;
        }

        resp.setContentType("text/plain");
        PrintWriter pw = resp.getWriter();
        pw.println(inviteLink.getUrl());
        pw.close();
    }
}
