-- SystemUptimeMonitor — PostgreSQL Schema (Multi-Tenant)
--
-- PUBLIC schema: only the organization registry table
-- Per-org schemas (e.g. org_example_com): fully isolated org data
--   including users, invites, monitors, incidents, etc.
--
-- On startup, DBManager.initSchema() creates the public organizations table.
-- SchemaManager.createOrgSchema() creates per-org schemas when
-- the first user registers for a new organization.

-- ===== PUBLIC SCHEMA (organization registry only) =====

CREATE TABLE IF NOT EXISTS organizations (
    id          SERIAL       PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    schema_name VARCHAR(255) NOT NULL UNIQUE
);

-- ===== PER-ORG SCHEMA TEMPLATE =====
-- The tables below are created inside each org's schema
-- (e.g., "org_example_com") by SchemaManager.createOrgSchema().
-- They are shown here for documentation purposes.
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.users (
--     id           SERIAL       PRIMARY KEY,
--     email        VARCHAR(255) NOT NULL UNIQUE,
--     password     VARCHAR(255) NOT NULL,
--     role         VARCHAR(50)  NOT NULL,
--     organization VARCHAR(255) NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.invites (
--     id           SERIAL       PRIMARY KEY,
--     created_by   INTEGER      NOT NULL REFERENCES <org_schema>.users(id),
--     created_time TIMESTAMP    NOT NULL,
--     expired      BOOLEAN      NOT NULL DEFAULT FALSE,
--     url          VARCHAR(255) NOT NULL UNIQUE,
--     role         VARCHAR(50)  NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.monitors (
--     id             SERIAL        PRIMARY KEY,
--     name           VARCHAR(255)  NOT NULL,
--     target_url     VARCHAR(2048) NOT NULL,
--     check_interval INTEGER       NOT NULL,
--     created_time   TIMESTAMP     NOT NULL,
--     created_by     INTEGER       NOT NULL REFERENCES <org_schema>.users(id),
--     failure_count  INTEGER       NOT NULL DEFAULT 0,
--     organization   VARCHAR(255)  NOT NULL,
--     enabled        BOOLEAN       NOT NULL DEFAULT TRUE
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.monitor_runs (
--     id            SERIAL    PRIMARY KEY,
--     monitor_id    INTEGER   NOT NULL REFERENCES <org_schema>.monitors(id) ON DELETE CASCADE,
--     time          TIMESTAMP NOT NULL,
--     response_time INTEGER   NOT NULL,
--     status_code   INTEGER   NOT NULL,
--     success       BOOLEAN   NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.incidents (
--     id                   SERIAL    PRIMARY KEY,
--     monitor_run_id       INTEGER   NOT NULL REFERENCES <org_schema>.monitor_runs(id) ON DELETE CASCADE,
--     down_time            TIMESTAMP NOT NULL,
--     resolved_time        TIMESTAMP,
--     status_code          INTEGER   NOT NULL,
--     expected_status_codes VARCHAR(255),
--     resolved             BOOLEAN   NOT NULL DEFAULT FALSE,
--     notes                TEXT
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.status_codes (
--     monitor_id  INTEGER NOT NULL REFERENCES <org_schema>.monitors(id) ON DELETE CASCADE,
--     status_code INTEGER NOT NULL,
--     PRIMARY KEY (monitor_id, status_code)
-- );
--
-- CREATE TABLE IF NOT EXISTS <org_schema>.monitor_audits (
--     id         SERIAL      PRIMARY KEY,
--     monitor_id INTEGER     NOT NULL,
--     operation  VARCHAR(50) NOT NULL,
--     time       TIMESTAMP   NOT NULL
-- );
