package org.example.systemuptimemonitor.resources;

import javax.ws.rs.*;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.example.systemuptimemonitor.filter.AdminAuth;
import org.example.systemuptimemonitor.model.InviteLink;
import org.example.systemuptimemonitor.model.User;
import org.example.systemuptimemonitor.services.InviteLinkService;
import org.example.systemuptimemonitor.services.UserService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

@Path("/")
@AdminAuth
public class AdminResource {

    private static final Logger LOG = Logger.getLogger(AdminResource.class.getName());

    @GET
    @Path("generate_invitelink")
    @Produces(MediaType.TEXT_PLAIN)
    public Response generateInviteLink(@QueryParam("role") String role,
                                       @Context ContainerRequestContext crc) {
        User user = (User) crc.getProperty("user");

        if (role == null || (!role.equals("operator") && !role.equals("viewer"))) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Role should be either operator or viewer\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        InviteLink inviteLink = new InviteLink(user.getId(), System.currentTimeMillis(), false,
                "" + System.currentTimeMillis(), role);

        try {
            new InviteLinkService().createInviteLink(inviteLink, user.getOrganization());
            LOG.info("Invite link generated by user " + user.getEmail() + " for role: " + role);
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Failed to generate invite link", e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\":\"Server error\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        return Response.ok(inviteLink.getUrl(), MediaType.TEXT_PLAIN).build();
    }

    @DELETE
    @Path("delete_user")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response deleteUser(@FormParam("delete_email") String email,
                               @Context ContainerRequestContext crc) {
        User user = (User) crc.getProperty("user");

        if (email == null || email.isEmpty()) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Not a valid email\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        try {
            new UserService().deleteUser(email, user.getOrganization());
            LOG.info("User deleted: " + email);
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Failed to delete user: " + email, e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\":\"Failed to delete user\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        return Response.ok().build();
    }

    @GET
    @Path("users")
    @Produces(MediaType.APPLICATION_JSON)
    public Response getUsers(@Context ContainerRequestContext crc) {
        User user = (User) crc.getProperty("user");

        try {
            List<User> users = new UserService().getUsers(user.getOrganization());
            StringBuilder json = new StringBuilder("{\"users\":[");
            for (int i = 0; i < users.size(); i++) {
                User u = users.get(i);
                if (i > 0) json.append(",");
                json.append("{\"id\":").append(u.getId())
                    .append(",\"email\":\"").append(u.getEmail()).append("\"")
                    .append(",\"role\":\"").append(u.getRole()).append("\"}");
            }
            json.append("]}");
            return Response.ok(json.toString(), MediaType.APPLICATION_JSON).build();
        } catch (Exception e) {
            LOG.log(Level.SEVERE, "Failed to get users", e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\":\"Failed to get users\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }
    }

    @PUT
    @Path("update_role")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response updateUserRole(@FormParam("user_id") String userIdStr,
                                   @FormParam("role") String role,
                                   @Context ContainerRequestContext crc) {
        User user = (User) crc.getProperty("user");

        if (userIdStr == null || userIdStr.isEmpty() || role == null || role.isEmpty()) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"user_id and role are required\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        if (!role.equals("operator") && !role.equals("viewer")) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Role must be operator or viewer\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        int userId;
        try {
            userId = Integer.parseInt(userIdStr);
        } catch (NumberFormatException e) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Invalid user_id\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        if (userId == user.getId()) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Cannot change your own role\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        try {
            new UserService().updateUserRole(userId, role, user.getOrganization());
            LOG.info("User role updated: userId=" + userId + " role=" + role);
        } catch (Exception e) {
            LOG.log(Level.SEVERE, "Failed to update user role: userId=" + userId, e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\":\"Failed to update user role\"}")
                    .type(MediaType.APPLICATION_JSON)
                    .build();
        }

        return Response.ok().build();
    }
}
